---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
    requirements-file: "${MOLECULE_SCENARIO_DIRECTORY}/requirements.yml"
driver:
  name: vagrant
lint: "${MOLECULE_SCENARIO_DIRECTORY}/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    box: centos/7
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_centos_7.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_centos_7.vdi']"
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7

  - name: "centos8-${INSTANCE_UUID:-1}"
    box: centos/stream8
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_centos_8.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_centos_8.vdi']"
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8

  - name: "fedora34-${INSTANCE_UUID:-1}"
    box: fedora/34-cloud-base
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_fedora_34.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_fedora_34.vdi']"
    memory: 3072
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
  - name: "fedora35-${INSTANCE_UUID:-1}"
    box: fedora/35-cloud-base
    provider_raw_config_args:
      - "customize
         ['createhd',
          '--filename', 'extradisk_fedora_35.vdi',
          '--size', 1024]"
      - "customize
         ['storageattach', :id,
          '--storagectl', 'IDE',
          '--port', 1,
          '--device', 1,
          '--type', 'hdd',
          '--medium', 'extradisk_fedora_35.vdi']"
    memory: 2048
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_35
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  inventory:
    hosts:
      molecule_hosts:
        vars:
          parted_disks_test:
            - device: /dev/sdb
              number: 1
              part_type: primary
              state: present
          parted_disks_load_from_hostvars: yes
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
