---

- name: Verify
  hosts: molecule_hosts
  gather_facts: yes
  tasks:
    - name: Assert desired partition is created
      assert:
        that:
          - ansible_facts.devices.sdb.partitions.sdb1 is defined
